// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ACLRuleAccess.
const (
	Deny ACLRuleAccess = "deny"
	Ro   ACLRuleAccess = "ro"
	Rw   ACLRuleAccess = "rw"
)

// Valid indicates whether the value is a known member of the ACLRuleAccess enum.
func (e ACLRuleAccess) Valid() bool {
	switch e {
	case Deny:
		return true
	case Ro:
		return true
	case Rw:
		return true
	default:
		return false
	}
}

// Defines values for Backend.
const (
	Gdrive Backend = "gdrive"
	Local  Backend = "local"
)

// Valid indicates whether the value is a known member of the Backend enum.
func (e Backend) Valid() bool {
	switch e {
	case Gdrive:
		return true
	case Local:
		return true
	default:
		return false
	}
}

// Defines values for EgressRuleMethods.
const (
	DELETE  EgressRuleMethods = "DELETE"
	GET     EgressRuleMethods = "GET"
	HEAD    EgressRuleMethods = "HEAD"
	OPTIONS EgressRuleMethods = "OPTIONS"
	PATCH   EgressRuleMethods = "PATCH"
	POST    EgressRuleMethods = "POST"
	PUT     EgressRuleMethods = "PUT"
)

// Valid indicates whether the value is a known member of the EgressRuleMethods enum.
func (e EgressRuleMethods) Valid() bool {
	switch e {
	case DELETE:
		return true
	case GET:
		return true
	case HEAD:
		return true
	case OPTIONS:
		return true
	case PATCH:
		return true
	case POST:
		return true
	case PUT:
		return true
	default:
		return false
	}
}

// ACLRule One access control rule.
type ACLRule struct {
	// Access Read-write, read-only, or fully denied.
	Access ACLRuleAccess `json:"access"`

	// Path Path or glob the rule applies to (for example
	// `/workspace/secret/**`). Rules are matched
	// longest-prefix-first; access is denied by default when
	// no rule matches.
	Path string `json:"path"`
}

// ACLRuleAccess Read-write, read-only, or fully denied.
type ACLRuleAccess string

// Agent The workload that runs inside the sandbox. Defined at sandbox
// creation time and not modifiable through this API.
type Agent struct {
	// Env Additional environment variables in `KEY=VALUE` form.
	Env *[]string `json:"env,omitempty"`

	// Image Reference to the agent image to launch.
	Image *string `json:"image,omitempty"`
}

// ApplyResult The outcome of an apply call.
type ApplyResult struct {
	// Applied `true` if every change was applied successfully. `false`
	// if the apply failed and was rolled back; in that case the
	// sandbox is unchanged.
	Applied bool `json:"applied"`

	// Changes Concrete additions and removals carried out by the apply. Each
	// list contains whole entries (a complete `FileSystem` or
	// `EgressRule`) so the caller can audit what was changed without
	// re-diffing the request.
	Changes Changes `json:"changes"`

	// Config A complete sandbox configuration.
	Config SandboxConfig `json:"config"`

	// Error Human-readable failure reason. Set only when `applied` is `false`.
	Error *string `json:"error,omitempty"`
}

// Backend Storage type for a file system.
//   - `local`  — sandbox-local storage with no external dependency.
//   - `gdrive` — backed by Google Drive.
type Backend string

// Changes Concrete additions and removals carried out by the apply. Each
// list contains whole entries (a complete `FileSystem` or
// `EgressRule`) so the caller can audit what was changed without
// re-diffing the request.
type Changes struct {
	Egress *struct {
		Added   *[]EgressRule `json:"added,omitempty"`
		Removed *[]EgressRule `json:"removed,omitempty"`
	} `json:"egress,omitempty"`
	Fs *struct {
		Added   *[]FileSystem `json:"added,omitempty"`
		Removed *[]FileSystem `json:"removed,omitempty"`
	} `json:"fs,omitempty"`

	// Warnings Non-fatal advisories. Example: a non-modifiable field was
	// present in the request and was ignored.
	Warnings *[]string `json:"warnings,omitempty"`
}

// Egress Network egress configuration.
type Egress struct {
	// Allow Ordered list of allow rules. The first rule that matches a
	// request decides the outcome; requests that match no rule
	// are denied.
	Allow *[]EgressRule `json:"allow,omitempty"`
}

// EgressRule One egress allow rule.
type EgressRule struct {
	// Headers Headers added to outbound requests that match this rule.
	// The agent cannot see or override these values.
	Headers *map[string]string `json:"headers,omitempty"`

	// Host Exact host (`api.github.com`) or wildcard suffix
	// (`*.pypi.org`).
	Host string `json:"host"`

	// Methods HTTP methods allowed by this rule. Empty means any method.
	Methods *[]EgressRuleMethods `json:"methods,omitempty"`

	// Paths Glob path patterns allowed by this rule. Empty means any
	// path.
	Paths *[]string `json:"paths,omitempty"`
}

// EgressRuleMethods defines model for EgressRule.Methods.
type EgressRuleMethods string

// Error defines model for Error.
type Error struct {
	// Details Optional structured context such as the offending field
	// path or a conflict identifier.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Human-readable failure reason.
	Error string `json:"error"`
}

// FileSystem A file system exposed to the agent at `mount`. The `backend`
// selects the storage type. Access is governed by `acls`,
// evaluated longest-prefix-first with deny as the default.
type FileSystem struct {
	// Acls Access control rules for paths under `mount`.
	Acls *[]ACLRule `json:"acls,omitempty"`

	// Backend Storage type for a file system.
	//   * `local`  — sandbox-local storage with no external dependency.
	//   * `gdrive` — backed by Google Drive.
	Backend Backend `json:"backend"`

	// GdriveAccessToken OAuth access token. Only used when `backend = gdrive`.
	GdriveAccessToken *string `json:"gdrive_access_token,omitempty"`

	// GdriveClientId OAuth client ID. Only used when `backend = gdrive`.
	GdriveClientId *string `json:"gdrive_client_id,omitempty"`

	// GdriveClientSecret OAuth client secret. Only used when `backend = gdrive`.
	GdriveClientSecret *string `json:"gdrive_client_secret,omitempty"`

	// GdriveFolderId ID of the Drive folder the file system is scoped to. When
	// omitted, the account root is used. Only used when
	// `backend = gdrive`.
	GdriveFolderId *string `json:"gdrive_folder_id,omitempty"`

	// GdriveRefreshToken OAuth refresh token. Only used when `backend = gdrive`.
	GdriveRefreshToken *string `json:"gdrive_refresh_token,omitempty"`

	// GdriveServiceAccountJson Service account credential JSON. Mutually exclusive with
	// the OAuth fields above. Only used when `backend = gdrive`.
	GdriveServiceAccountJson *string `json:"gdrive_service_account_json,omitempty"`

	// Mount Absolute path at which the file system appears to the agent.
	Mount string `json:"mount"`
}

// JSONRPCError defines model for JSONRPCError.
type JSONRPCError struct {
	// Code Standard JSON-RPC error code. `-32700` parse error,
	// `-32600` invalid request, `-32601` method not found,
	// `-32602` invalid params, `-32603` internal error.
	// Application errors use codes in the range `-32000` to
	// `-32099`.
	Code int `json:"code"`

	// Data Optional structured error context.
	Data    interface{} `json:"data,omitempty"`
	Message string      `json:"message"`
}

// JSONRPCNotification A JSON-RPC 2.0 notification envelope (no `id`, no response
// expected).
type JSONRPCNotification struct {
	Jsonrpc string                      `json:"jsonrpc"`
	Method  string                      `json:"method"`
	Params  *JSONRPCNotification_Params `json:"params,omitempty"`
}

// JSONRPCNotificationParams0 defines model for .
type JSONRPCNotificationParams0 map[string]interface{}

// JSONRPCNotificationParams1 defines model for .
type JSONRPCNotificationParams1 = []interface{}

// JSONRPCNotification_Params defines model for JSONRPCNotification.Params.
type JSONRPCNotification_Params struct {
	union json.RawMessage
}

// JSONRPCRequest A JSON-RPC 2.0 request envelope.
type JSONRPCRequest struct {
	// Id Client-chosen request identifier echoed back in the response.
	Id      JSONRPCRequest_Id `json:"id"`
	Jsonrpc string            `json:"jsonrpc"`

	// Method MCP method name, e.g. `initialize`, `tools/list`,
	// `tools/call`, `resources/list`, `resources/read`,
	// `prompts/list`, `prompts/get`.
	Method string `json:"method"`

	// Params Method parameters. Schema depends on `method`.
	Params *JSONRPCRequest_Params `json:"params,omitempty"`
}

// JSONRPCRequestId0 defines model for .
type JSONRPCRequestId0 = string

// JSONRPCRequestId1 defines model for .
type JSONRPCRequestId1 = int

// JSONRPCRequest_Id Client-chosen request identifier echoed back in the response.
type JSONRPCRequest_Id struct {
	union json.RawMessage
}

// JSONRPCRequestParams0 defines model for .
type JSONRPCRequestParams0 map[string]interface{}

// JSONRPCRequestParams1 defines model for .
type JSONRPCRequestParams1 = []interface{}

// JSONRPCRequest_Params Method parameters. Schema depends on `method`.
type JSONRPCRequest_Params struct {
	union json.RawMessage
}

// JSONRPCResponse A JSON-RPC 2.0 response envelope. Exactly one of `result` or
// `error` is present.
type JSONRPCResponse struct {
	Error   *JSONRPCError      `json:"error,omitempty"`
	Id      JSONRPCResponse_Id `json:"id"`
	Jsonrpc string             `json:"jsonrpc"`

	// Result Method result. Shape depends on the called method — for
	// example, `tools/call` returns a `CallToolResult` with a
	// `content` array and `isError` flag.
	Result interface{} `json:"result,omitempty"`
}

// JSONRPCResponseId0 defines model for .
type JSONRPCResponseId0 = string

// JSONRPCResponseId1 defines model for .
type JSONRPCResponseId1 = int

// JSONRPCResponse_Id defines model for JSONRPCResponse.Id.
type JSONRPCResponse_Id struct {
	union json.RawMessage
}

// SandboxConfig A complete sandbox configuration.
type SandboxConfig struct {
	// Agent The workload that runs inside the sandbox. Defined at sandbox
	// creation time and not modifiable through this API.
	Agent *Agent `json:"agent,omitempty"`

	// AuditDir Directory where audit logs are written.
	AuditDir string `json:"audit_dir"`

	// Egress Network egress configuration.
	Egress *Egress `json:"egress,omitempty"`

	// Fs One or more file systems exposed to the agent. Mount paths
	// must be unique and non-overlapping (a mount path may not
	// be a parent directory of another mount path).
	Fs []FileSystem `json:"fs"`
}

// McpStreamParams defines parameters for McpStream.
type McpStreamParams struct {
	McpSessionId *string `json:"Mcp-Session-Id,omitempty"`
}

// McpRequestJSONBody defines parameters for McpRequest.
type McpRequestJSONBody struct {
	union json.RawMessage
}

// McpRequestParams defines parameters for McpRequest.
type McpRequestParams struct {
	// McpSessionId Optional client-supplied session identifier.
	McpSessionId *string `json:"Mcp-Session-Id,omitempty"`
}

// McpRequestJSONBody2 defines parameters for McpRequest.
type McpRequestJSONBody2 = []McpRequestJSONBody_2_Item

// McpRequestJSONBody_2_Item defines parameters for McpRequest.
type McpRequestJSONBody_2_Item struct {
	union json.RawMessage
}

// McpRequest200JSONResponseBody1 defines parameters for McpRequest.
type McpRequest200JSONResponseBody1 = []JSONRPCResponse

// McpRequest200JSONResponseBody defines parameters for McpRequest.
type McpRequest200JSONResponseBody struct {
	union json.RawMessage
}

// ApplyConfigJSONRequestBody defines body for ApplyConfig for application/json ContentType.
type ApplyConfigJSONRequestBody = SandboxConfig

// McpRequestJSONRequestBody defines body for McpRequest for application/json ContentType.
type McpRequestJSONRequestBody McpRequestJSONBody

// AsJSONRPCNotificationParams0 returns the union data inside the JSONRPCNotification_Params as a JSONRPCNotificationParams0
func (t JSONRPCNotification_Params) AsJSONRPCNotificationParams0() (JSONRPCNotificationParams0, error) {
	var body JSONRPCNotificationParams0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCNotificationParams0 overwrites any union data inside the JSONRPCNotification_Params as the provided JSONRPCNotificationParams0
func (t *JSONRPCNotification_Params) FromJSONRPCNotificationParams0(v JSONRPCNotificationParams0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCNotificationParams0 performs a merge with any union data inside the JSONRPCNotification_Params, using the provided JSONRPCNotificationParams0
func (t *JSONRPCNotification_Params) MergeJSONRPCNotificationParams0(v JSONRPCNotificationParams0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJSONRPCNotificationParams1 returns the union data inside the JSONRPCNotification_Params as a JSONRPCNotificationParams1
func (t JSONRPCNotification_Params) AsJSONRPCNotificationParams1() (JSONRPCNotificationParams1, error) {
	var body JSONRPCNotificationParams1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCNotificationParams1 overwrites any union data inside the JSONRPCNotification_Params as the provided JSONRPCNotificationParams1
func (t *JSONRPCNotification_Params) FromJSONRPCNotificationParams1(v JSONRPCNotificationParams1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCNotificationParams1 performs a merge with any union data inside the JSONRPCNotification_Params, using the provided JSONRPCNotificationParams1
func (t *JSONRPCNotification_Params) MergeJSONRPCNotificationParams1(v JSONRPCNotificationParams1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JSONRPCNotification_Params) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JSONRPCNotification_Params) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJSONRPCRequestId0 returns the union data inside the JSONRPCRequest_Id as a JSONRPCRequestId0
func (t JSONRPCRequest_Id) AsJSONRPCRequestId0() (JSONRPCRequestId0, error) {
	var body JSONRPCRequestId0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCRequestId0 overwrites any union data inside the JSONRPCRequest_Id as the provided JSONRPCRequestId0
func (t *JSONRPCRequest_Id) FromJSONRPCRequestId0(v JSONRPCRequestId0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCRequestId0 performs a merge with any union data inside the JSONRPCRequest_Id, using the provided JSONRPCRequestId0
func (t *JSONRPCRequest_Id) MergeJSONRPCRequestId0(v JSONRPCRequestId0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJSONRPCRequestId1 returns the union data inside the JSONRPCRequest_Id as a JSONRPCRequestId1
func (t JSONRPCRequest_Id) AsJSONRPCRequestId1() (JSONRPCRequestId1, error) {
	var body JSONRPCRequestId1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCRequestId1 overwrites any union data inside the JSONRPCRequest_Id as the provided JSONRPCRequestId1
func (t *JSONRPCRequest_Id) FromJSONRPCRequestId1(v JSONRPCRequestId1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCRequestId1 performs a merge with any union data inside the JSONRPCRequest_Id, using the provided JSONRPCRequestId1
func (t *JSONRPCRequest_Id) MergeJSONRPCRequestId1(v JSONRPCRequestId1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JSONRPCRequest_Id) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JSONRPCRequest_Id) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJSONRPCRequestParams0 returns the union data inside the JSONRPCRequest_Params as a JSONRPCRequestParams0
func (t JSONRPCRequest_Params) AsJSONRPCRequestParams0() (JSONRPCRequestParams0, error) {
	var body JSONRPCRequestParams0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCRequestParams0 overwrites any union data inside the JSONRPCRequest_Params as the provided JSONRPCRequestParams0
func (t *JSONRPCRequest_Params) FromJSONRPCRequestParams0(v JSONRPCRequestParams0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCRequestParams0 performs a merge with any union data inside the JSONRPCRequest_Params, using the provided JSONRPCRequestParams0
func (t *JSONRPCRequest_Params) MergeJSONRPCRequestParams0(v JSONRPCRequestParams0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJSONRPCRequestParams1 returns the union data inside the JSONRPCRequest_Params as a JSONRPCRequestParams1
func (t JSONRPCRequest_Params) AsJSONRPCRequestParams1() (JSONRPCRequestParams1, error) {
	var body JSONRPCRequestParams1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCRequestParams1 overwrites any union data inside the JSONRPCRequest_Params as the provided JSONRPCRequestParams1
func (t *JSONRPCRequest_Params) FromJSONRPCRequestParams1(v JSONRPCRequestParams1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCRequestParams1 performs a merge with any union data inside the JSONRPCRequest_Params, using the provided JSONRPCRequestParams1
func (t *JSONRPCRequest_Params) MergeJSONRPCRequestParams1(v JSONRPCRequestParams1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JSONRPCRequest_Params) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JSONRPCRequest_Params) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJSONRPCResponseId0 returns the union data inside the JSONRPCResponse_Id as a JSONRPCResponseId0
func (t JSONRPCResponse_Id) AsJSONRPCResponseId0() (JSONRPCResponseId0, error) {
	var body JSONRPCResponseId0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCResponseId0 overwrites any union data inside the JSONRPCResponse_Id as the provided JSONRPCResponseId0
func (t *JSONRPCResponse_Id) FromJSONRPCResponseId0(v JSONRPCResponseId0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCResponseId0 performs a merge with any union data inside the JSONRPCResponse_Id, using the provided JSONRPCResponseId0
func (t *JSONRPCResponse_Id) MergeJSONRPCResponseId0(v JSONRPCResponseId0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJSONRPCResponseId1 returns the union data inside the JSONRPCResponse_Id as a JSONRPCResponseId1
func (t JSONRPCResponse_Id) AsJSONRPCResponseId1() (JSONRPCResponseId1, error) {
	var body JSONRPCResponseId1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCResponseId1 overwrites any union data inside the JSONRPCResponse_Id as the provided JSONRPCResponseId1
func (t *JSONRPCResponse_Id) FromJSONRPCResponseId1(v JSONRPCResponseId1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCResponseId1 performs a merge with any union data inside the JSONRPCResponse_Id, using the provided JSONRPCResponseId1
func (t *JSONRPCResponse_Id) MergeJSONRPCResponseId1(v JSONRPCResponseId1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t JSONRPCResponse_Id) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *JSONRPCResponse_Id) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJSONRPCRequest returns the union data inside the McpRequestJSONBody as a JSONRPCRequest
func (t McpRequestJSONBody) AsJSONRPCRequest() (JSONRPCRequest, error) {
	var body JSONRPCRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCRequest overwrites any union data inside the McpRequestJSONBody as the provided JSONRPCRequest
func (t *McpRequestJSONBody) FromJSONRPCRequest(v JSONRPCRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCRequest performs a merge with any union data inside the McpRequestJSONBody, using the provided JSONRPCRequest
func (t *McpRequestJSONBody) MergeJSONRPCRequest(v JSONRPCRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJSONRPCNotification returns the union data inside the McpRequestJSONBody as a JSONRPCNotification
func (t McpRequestJSONBody) AsJSONRPCNotification() (JSONRPCNotification, error) {
	var body JSONRPCNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCNotification overwrites any union data inside the McpRequestJSONBody as the provided JSONRPCNotification
func (t *McpRequestJSONBody) FromJSONRPCNotification(v JSONRPCNotification) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCNotification performs a merge with any union data inside the McpRequestJSONBody, using the provided JSONRPCNotification
func (t *McpRequestJSONBody) MergeJSONRPCNotification(v JSONRPCNotification) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMcpRequestJSONBody2 returns the union data inside the McpRequestJSONBody as a McpRequestJSONBody2
func (t McpRequestJSONBody) AsMcpRequestJSONBody2() (McpRequestJSONBody2, error) {
	var body McpRequestJSONBody2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMcpRequestJSONBody2 overwrites any union data inside the McpRequestJSONBody as the provided McpRequestJSONBody2
func (t *McpRequestJSONBody) FromMcpRequestJSONBody2(v McpRequestJSONBody2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpRequestJSONBody2 performs a merge with any union data inside the McpRequestJSONBody, using the provided McpRequestJSONBody2
func (t *McpRequestJSONBody) MergeMcpRequestJSONBody2(v McpRequestJSONBody2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t McpRequestJSONBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *McpRequestJSONBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJSONRPCRequest returns the union data inside the McpRequestJSONBody_2_Item as a JSONRPCRequest
func (t McpRequestJSONBody_2_Item) AsJSONRPCRequest() (JSONRPCRequest, error) {
	var body JSONRPCRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCRequest overwrites any union data inside the McpRequestJSONBody_2_Item as the provided JSONRPCRequest
func (t *McpRequestJSONBody_2_Item) FromJSONRPCRequest(v JSONRPCRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCRequest performs a merge with any union data inside the McpRequestJSONBody_2_Item, using the provided JSONRPCRequest
func (t *McpRequestJSONBody_2_Item) MergeJSONRPCRequest(v JSONRPCRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsJSONRPCNotification returns the union data inside the McpRequestJSONBody_2_Item as a JSONRPCNotification
func (t McpRequestJSONBody_2_Item) AsJSONRPCNotification() (JSONRPCNotification, error) {
	var body JSONRPCNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCNotification overwrites any union data inside the McpRequestJSONBody_2_Item as the provided JSONRPCNotification
func (t *McpRequestJSONBody_2_Item) FromJSONRPCNotification(v JSONRPCNotification) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCNotification performs a merge with any union data inside the McpRequestJSONBody_2_Item, using the provided JSONRPCNotification
func (t *McpRequestJSONBody_2_Item) MergeJSONRPCNotification(v JSONRPCNotification) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t McpRequestJSONBody_2_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *McpRequestJSONBody_2_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsJSONRPCResponse returns the union data inside the McpRequest200JSONResponseBody as a JSONRPCResponse
func (t McpRequest200JSONResponseBody) AsJSONRPCResponse() (JSONRPCResponse, error) {
	var body JSONRPCResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromJSONRPCResponse overwrites any union data inside the McpRequest200JSONResponseBody as the provided JSONRPCResponse
func (t *McpRequest200JSONResponseBody) FromJSONRPCResponse(v JSONRPCResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeJSONRPCResponse performs a merge with any union data inside the McpRequest200JSONResponseBody, using the provided JSONRPCResponse
func (t *McpRequest200JSONResponseBody) MergeJSONRPCResponse(v JSONRPCResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsMcpRequest200JSONResponseBody1 returns the union data inside the McpRequest200JSONResponseBody as a McpRequest200JSONResponseBody1
func (t McpRequest200JSONResponseBody) AsMcpRequest200JSONResponseBody1() (McpRequest200JSONResponseBody1, error) {
	var body McpRequest200JSONResponseBody1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMcpRequest200JSONResponseBody1 overwrites any union data inside the McpRequest200JSONResponseBody as the provided McpRequest200JSONResponseBody1
func (t *McpRequest200JSONResponseBody) FromMcpRequest200JSONResponseBody1(v McpRequest200JSONResponseBody1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMcpRequest200JSONResponseBody1 performs a merge with any union data inside the McpRequest200JSONResponseBody, using the provided McpRequest200JSONResponseBody1
func (t *McpRequest200JSONResponseBody) MergeMcpRequest200JSONResponseBody1(v McpRequest200JSONResponseBody1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t McpRequest200JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *McpRequest200JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Read the current configuration.
	// (GET /v1/config)
	GetConfig(c *gin.Context)
	// Apply a desired configuration.
	// (PUT /v1/config)
	ApplyConfig(c *gin.Context)
	// Open a server-to-client SSE stream.
	// (GET /v1/mcp)
	McpStream(c *gin.Context, params McpStreamParams)
	// Send an MCP request.
	// (POST /v1/mcp)
	McpRequest(c *gin.Context, params McpRequestParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetConfig(c)
}

// ApplyConfig operation middleware
func (siw *ServerInterfaceWrapper) ApplyConfig(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ApplyConfig(c)
}

// McpStream operation middleware
func (siw *ServerInterfaceWrapper) McpStream(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params McpStreamParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Mcp-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Mcp-Session-Id")]; found {
		var McpSessionId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Mcp-Session-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Mcp-Session-Id", valueList[0], &McpSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Mcp-Session-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.McpSessionId = &McpSessionId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.McpStream(c, params)
}

// McpRequest operation middleware
func (siw *ServerInterfaceWrapper) McpRequest(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params McpRequestParams

	headers := c.Request.Header

	// ------------- Optional header parameter "Mcp-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Mcp-Session-Id")]; found {
		var McpSessionId string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for Mcp-Session-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Mcp-Session-Id", valueList[0], &McpSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter Mcp-Session-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.McpSessionId = &McpSessionId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.McpRequest(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v1/config", wrapper.GetConfig)
	router.PUT(options.BaseURL+"/v1/config", wrapper.ApplyConfig)
	router.GET(options.BaseURL+"/v1/mcp", wrapper.McpStream)
	router.POST(options.BaseURL+"/v1/mcp", wrapper.McpRequest)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFvvcts4kn+VLs5VbZKTaCeze7PjqfngdXSJ75LYZ3t27yrKhTDZlLABAQ4AytalXLUPsU+4T3LVDZAi",
	"JfpfJtn5kLFEEGg0+s+vfw19TnJT1Uaj9i45+Jy4fImV4D8Pj96cNQrpT1EU0kujhTq1pkbrJbrkoBTK",
	"4SQp0OVW1vQ8OUhONILIc3QOcqO9NQpsozBNJknde/dzEgbRX8MJzlAU0ysrPU7A0t9Gq/UEjIWyUWoN",
	"BWqJBc2HuqmSg/eJvUomiTUJiaLXyYdJ4tc1JgeJ81bqRXIzSWrhl7tLnQq/pIkXylyCXyJLCqKulUQH",
	"3sCT0ljAa1HVCuc627sy9pOrRY57DnOLfu/Zs+xpCqQmB8IiVMLnSyzmWhm9QOentcVSXk9LaZ3/qVWM",
	"dHEXcEn7KUWjPFwtUc+1NkGIMJFL55o2GiRIDpIxCZKd/d5MEou/NtJiQfrhzU9ahW/UYy7/irkn9Rwu",
	"UPtHHvTFEoGkUUYU4JfCg220A6mdLJC16YQuLs11Ci+xlBoLEL79bq5zi4JmAi8rBKEL0MZDZQpZSnGp",
	"aAZrmsUS/FI6ODw9DqoY2hDq1e6pHnZ7ANQraY2uUHtYCcsTk4iQ/efsf37+8+GbX2YZlMZWaV/L75M3",
	"J68+vpn9efbmZ6lLMqyz2avjk3c/N26Kwvnpc9Ki9FixFDvWFr8Q1oo1fZaVWOCYpZdoUedIpkYKE3QM",
	"wKPpKyUanS8HoiXVesqjDpTw6Pzo2e8eb12r9Rm6Rn3JIZvG56ZCMCUIzd6xhlwoNeLS7DnF7k4zbxvM",
	"QJaAK7RryJdCLxCuhIveVoBr2DzZx1PIWJpsrmUZNMOrlkIqMiNd8KvWKPp4KfJPP9GhshHmwrH1zXU0",
	"NfI20iOtWAQjigq6NEah0KSh8Jg38S8Wy+Qg+W5vExj3YlTcO4rD6A2jS7m474XzIMNRGHwzSdBaY3cV",
	"9LqphJ5SuGPbp402Fin+OaNTOEcPFAY5SEAWdZbR1qKm0nujQHs4neibXY+FhD+J/BPqkbM898ayga5r",
	"JN8BAaVUCG7tPFbpXAM8g0yZXKgM4B9/+3vr81P+Dlx8/0r6JWgDeO3RkrMWWKMuUOfrdpJFYeUKM56E",
	"TjkEzFfGLBTCS3oW42NMBLxAMknCe6OJ4Ghz0I9wgyND8cojtO84NkKLlVkJ5SAX1pIRm8aThJ3FpjAT",
	"+XKulXSe06GQ2sHV0igE1N5SmnkigAxH0fTZv0uF56zIDIyd62y2sOgcJZjsKbgQJsj50EJO3tgUklKH",
	"8OwR0cpZt6bxc21xWsiylHoR8hv+2qDzo6GUF7pXL1sOXxTB3btYeJczbPYyFiRZmV9ptrEgWH7bzW1O",
	"7mts7q7ZxjZ3JayWejECp94ZPS2FFwpEsZLOkM2lMAsJ5QAEaKOnvbRbSlQcXue6tug4Iem+8XThVy60",
	"sW1IfWgyHBN+9jDT29oXekIfEOwWQkxrLGOKkcyklLnaVc6JLdBiAeyflN9oGAMwlwLlPsZtAZFxdomw",
	"DAS5VlBHgbksCC5uUuVPra5c7y2I0G6uCShGFDvU3dc09974xwP4qNSNOnY1ukRRoL3j1EZMYSvnhRmA",
	"/Yzwjmn8pWk4ru5qj2EgizLXFx1WyoUm2OgQCcebFVob0adDWAnV7EDoz8l/T2NWnl6gFoR7E5FXfbVu",
	"tLg0zu+azexa5B7oGTzJRC3ThfTL5jLNTZU9JUGupCpyYQnVlKW8nusn2bO0XtcyNXaRPd1G9cMpkpG0",
	"VaFfmmLEvV9fXJxCfBrOKyTJjbpgVtV+DRUKzlrrOHoL8b6aXQwwbZtS6ftJcnpyzv/7hf89vDh6nUyS",
	"l7M3s4tZMklezw5fJpPk5PTi+OTd+Wja3Y6HVJKM7OYVFWL0jP4hWPDAPc01vbSl1vfJnsXauL1nj0Hr",
	"W6iJDWAMH81aIPeIjFKgF1Ld4TMEk3f8sY7FjPO2yX1D8YqgBF57As1LEDH2lCXqgjI9h/CgEmB8RsFR",
	"ydyDLFB7WUq0AyC82dUXwdN7oWeYdUyLvTz3uCh12AedgNe1cSGIbOoo4SGrTKN9FmJ5dhkgbTbXDhXm",
	"PujN9fBsCoddhb6gaKKD5WUiVy6bzDVSTBGeUsZIgR8wbYF63R5KLO7HABdNOVK87lInjlE2eww0ukDb",
	"beuhuaNlckYc8XID8++aoa0Gblpw/TGwCR+9+YR6JLEeNn7Z0h08JoUTKmAaOqZQxcSl4WeIOJ/2Q8W4",
	"oJBcC+eujC3GomEUIVcStf8oi9vWDwPg+OUDF79nocC43LNYGPQNdlsaVaAd3e3xSwIvZG9cFEEYyl/0",
	"vUQ6cLmp2U9S+AvzTaaS3mMxCX6T52RYYI3xXDY7LLZ3MtcjW+kHkx3BLZYW3fJuU4mDvpmtOLQrmbPZ",
	"0hY//tWZEVnOw6hOEblFjphCwX+cn7xL4W3jG6HUGvA6V40jZZPPzzWpL+yEo68DcWlW+JCNsO4etBX2",
	"+pGQcemMajyGxEmV4FIyYBqevqhrFNYNYmR6C7mYcIamBJwcJP+7l/7rvSE+yLaJJ2PBnlR4dnr0JZkz",
	"NwWOURFCFwSzaObp2ekRcKYBGp1CNv3+xQ/7+xnUwjoMjyZzTV//G30t9Uoo2aHNCYQnz7OIkJiQLAmQ",
	"dm+92LxVCysq1770PT2IPAYvlM71YV0rmQeSk79jh2LhXFdTMQ9Gc+yTSN6ElfZ//HHoVDT5Ai2DaOHF",
	"iBeNoIRWGYwV0gAjnYtU5N3HyfrejL/jNN8ZAhRhm4/O4d25vUj3Sd3dTIB6hcrUCE+0gUwW2YTrJ3S1",
	"0Q7nGq9rzD0WT8dSKzm3rfNgOJoQfPIi3b8dV4/CwnDA9MhoPCmTg/d3o7ZtBW0q/Z20+2Fb3a3AnUB3",
	"KPwsmOtv03VbvLZq3q3vxvLMEae4ab40DnU3xwZUAuZLExnZDWsQjoxW2ChyW9ufdwz9w83ki85xKPHb",
	"o9POm0WFE8B0kUImtaSgLv8Pswlk3hjl9pR0niBe/JgLpeihRWcam2M7oP8NAWJ+pbamqv1mSPt5gT7b",
	"LvY20yeTu6xuayNhE/wYPVqXwjljs0ibOjAasrDVbKjrb2+0snig5QZT+K2mG2bZ2C5wPa7WYDR3KeiE",
	"GuUjg8pRkKnyyGeNsp9tTroLBA/y180kusi3M2rbdWxGbSE8TuF8KWrsm0HHERet7f/jb3+nIoLCJpth",
	"Z/Rs5WDRN1xrQ3YklLowRp1FFXJFI+Y64zSifQZsDkwCZtLNgnJLJRak1jtNZMwyhv2Rx9pFx5u3rZ77",
	"WMC2zXlnscSDbiYJc+sfCzlSD7+UFnNvLDdkLEYaXplF6AJfWQLVegtd8aCpafzYWW/o9/tJwA2bvcvc",
	"GQuVsQPk50bL4xTeMsTlunKuq8Z5uERotPy1afuxeko1sBJ1LfUCngioulegEmvK2HN9iSAoLlHxU3R6",
	"4Wah8Uu0vZeePoLvHDLgldTH4a3n9xA2pUv6R7drdPQCd3V39HexRHhNkP7w9DjqjHzCSb1Q5GC5EmRZ",
	"Kxza2VwXJm+4x0x+lg1sOjSvmMdsry/QkpfoQtdG6HAcc20brUnNuw107vQ4xNhzEvkyhfPmspI+cgyO",
	"Nj/XA6l4MD2mzZB+Gx9J6kpqWTUVOGTOOzYBA6FNE5GZ5Eav0C4w3ooIkrXisBkJD84LHztwrqkqYdcU",
	"nIQWCzKJOPp3bmiLbFlD7r6nWbXmOlx6dpn2MJJJskLrwintp8/TfbIJU6MWtUwOku/TfY6gHau4t3q+",
	"t2nQLsaK9rMY82iD20eWN5bMWa0JxGBZYs6VEoUS1u1xkRwkr9AftY3UNifx4i/292Nw9+2tik0lsNcW",
	"nsHOH9k/vrkZa9BHcbejHw3enMsZimAPt4yeJF4sHHnQUf9BQimrbkYUeGQq8vpIojWxjR+NcTh7yCK9",
	"xee6a/uTDbFRdNdulre2WTViQYbeM9AU+gdZG+en8YbCjjNQFovt3ww6l43+SPbdtVFDR8JYiG27dK5D",
	"04HSJSEJ4U0l8wOQJTPqUhdyJYtGqPZmQymkcoFUIXBsMex4TS/3ri2ENDrWzmevGhoc3+LomRyj7z+Z",
	"Yv0Aa4tpqKWeh7TrxkgOiwLEoME+oBC8oXiF19L5Xjwg7xSqwUGGjVdedu6rDPPqMCn2WtChXff+c2zA",
	"7HZIuoZI17qIzt9n/RlvUaZ839Kt7zf3zsK1sXAxrE99EG67Z8zes2fJzYceedrdPIgUze58dy4erivc",
	"vjA/3100XnO4hZJN1uLFj2mLP8ZoxOT5f/3FFP7V2zRN+7JHcT5wuPniOLVJylRq3HzDINm/3jQSIvkx",
	"CO+xqj0WKRxrV2Pue47HbhgTYcZMye+/onyxYBgP3l3kHAYs6VqmKYrz47cX55AqpJU0jYMuWDkvKeRp",
	"qK1h99zOK1G744H/rrRyM+E0XeX1rTn6pEauSs7RrtBOzylez1a0GXDeoqhC7uGnDJIaxxfn6sYt57rP",
	"J4VEYho/NeX0MiSVaI0tKg78fRoXc3PNGKcwTAMGwsAjREbM0VyM00zZEiF7G3YqFFSQ/X7/DxCrtXfG",
	"w2HoZY5G97d5fc57SiIJwFU+Bw1Jugj99mSSaFFhGD89R0egaHpM9ffm8LepvQ/3+p7Ha7+HpNlpUOzQ",
	"mrZZV1a9KTd1+a6quwXHuoM7lnd+PmtPlFAdtkb/hzGQTlYZjrww6Ph46MAfdDTb1ksWRlg1GJg309jF",
	"2QjUN+G3R6cBD43eCjimQFuxdZI9vTUFKjiKndpTa7zJjYKgPW6jvr64OJ1rb4V2tbE+dClbVu3SFOyA",
	"Ysh+tKTHT+GOY0eGSAcoudzqCpYNKd5xqaWx4GS4zbytGgY37mnoGN/ucU+YR1BGL6ZtXcAv8qm3QWJo",
	"EE8ZP333HVwYo1yLpeIZimJFBbqLyK805CN8X40Gd7eA+yTdAU0RLgii/5hH0B7uGlLSWQlFcnsD2avZ",
	"BWyKgSyFC/GJbYYmGPlP2AXDQvdTR4oMYOvoS1vlQ3t7kWNoJ96IcKe/jAonHrYMCAfSu07kTuLbtqYh",
	"62XKrD2UGET4XALBG+/dENoGF55yF0HqRvr14FL8hDZi0TV8h3uupZ6WSi6WvjUXUXq2ybbku1Syfsrk",
	"gUM/19kwjGVgOl7ZdaE4iCOda7iujBIdv+zirPTbbDOEcNm2RZ2okAngWyJvy6nvhN5bmiwhSky73N3K",
	"1LtfkUy+Ttz+UpRPTtmvGAY4/4jqmO6WarRR9rg+mCeM+KJHWEaesuXah0z2hrjufOg3FwSPhu4PxuQU",
	"xeOB9FUQchMFGQ5VQ6W9kc6DWAmpOHq/PToNMWpbZc/vVRktkGyh6w2N/AAKurVXKhkeMHzQo6N3biXY",
	"L4UPvzjoOLp/nlwfxloOX72QeOR+Ysei3xl55ItjbZTH4a3bcnG4XQ5ZIbw4yKAWa/4tjuQU0h1ptiVS",
	"Rhk+GzmB8WscY2VCN3d7EvzzLKF7sClcd2g7EfGCvIvpfdrUHVojY+vdJd0Kj7tXL0OHsZs9ogjpIAZ1",
	"ZlC7gFyZgjuPtwdZ2t+L/Rcj1yqGDWnmhfIcQwlJAKZFaFRWrr960bhjSOPlYwsXSTxCwgLC9YQd8LeN",
	"fM9RF3RkFMbanwXsQF1+JSThkXT4Mv5yrdd94UtrqIvayHC7pLGKkqD39cHeHkfkpXH+4I8//PEHDtdx",
	"vbEfAXas4LpPhv9u6653x+Slmxw7LDV3A94t0LyTG2aR/Gf7HXL9HXZwBMC6JADOgBJ60YgFTiuen9Oc",
	"47rUxu3M4++QBuz+5oduKC3o0GGgSadUzipj6snmBx1LoYupNUqRoZ/Nzi8C+g6u20KMo1OKM/8fAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
