# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: controller
generate:
  gin-server: true
  models: true
  embedded-spec: true
output: ./gen/controller/server.gen.go
output-options:
  skip-prune: true
import-mapping:
  ./config.yaml: "github.com/hiver-sh/hiver/internal/api/gen/sandbox"
