# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: gen
generate:
  models: true
output: ./gen/events.gen.go
output-options:
  skip-prune: true
import-mapping:
  ./config.yaml: "-"
