# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: sandbox
generate:
  gin-server: true
  models: true
  embedded-spec: true
output: ./gen/sandbox/server.gen.go
output-options:
  skip-prune: true
import-mapping:
  ./config.yaml: "-"
  ./events.yaml: "-"
