{{/*
hiver.envoyConfig renders the full Envoy bootstrap (the body of the
gateway-envoy ConfigMap's envoy.yaml key). The per-image create routes and
their STRICT_DNS clusters are generated by ranging .Values.sandboxServices, so they stay
in lockstep with the image-pools Deployments/Services. Rendered at indent 0;
the ConfigMap nindents it under the `|` block scalar.

Mirrors docker/gateway/envoy.yaml, with one deployment-specific change: the
sandbox cluster addresses are fully-qualified cross-namespace DNS names
(<image>.<sandbox-ns>.svc.cluster.local) so the gateway in the control-plane
namespace can reach sandbox Services in the sandbox namespace.
*/}}
{{- define "hiver.envoyConfig" -}}
static_resources:
  listeners:
    - name: main
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{ .Values.gateway.listenPort }}
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: gateway
                # Proxy WebSocket upgrades end-to-end. The sandbox ingress
                # exposes arbitrary upstream ports via
                # /sandbox/<id>/.../proxy/<port>, including Chrome's CDP/DevTools
                # endpoint that Playwright's connectOverCDP drives over a
                # WebSocket. Without this Envoy refuses the Upgrade and the CDP
                # handshake fails. Keep in sync with docker/gateway/envoy.yaml.
                upgrade_configs:
                  - upgrade_type: websocket
                # A CDP session can sit idle between commands; don't tear the
                # upgraded stream down on the default idle timeout. 0 disables it.
                stream_idle_timeout: 0s
                http_filters:
                  - name: envoy.filters.http.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
                      inline_code: |
                        function envoy_on_request(request_handle)
                          local path = request_handle:headers():get(":path")
                          local id = path:match("^/sandbox/([^/?#]+)")
                          if not id then
                            return
                          end
                          -- The id is a UUID whose first 4 bytes are the
                          -- sandbox pod's IPv4 address (assigned by the
                          -- controller at creation). Decode it and dial the
                          -- pod directly, bypassing the per-sandbox Service
                          -- DNS name — kube-dns negatively caches a fresh
                          -- sandbox's record for ~10s, which used to gate
                          -- time-to-route.
                          local hex = id:gsub("-", "")
                          local ip = string.format("%d.%d.%d.%d",
                            tonumber(hex:sub(1, 2), 16),
                            tonumber(hex:sub(3, 4), 16),
                            tonumber(hex:sub(5, 6), 16),
                            tonumber(hex:sub(7, 8), 16))
                          request_handle:headers():replace(":authority", ip .. ":{{ .Values.sandboxPort }}")
                        end
                  - name: envoy.filters.http.dynamic_forward_proxy
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.dynamic_forward_proxy.v3.FilterConfig
                      # Keep this block byte-identical to the dynamic_forward_proxy
                      # cluster's dns_cache_config below — Envoy keys the shared
                      # cache by name and rejects mismatched configs.
                      dns_cache_config:
                        name: dynamic_forward_proxy_cache_config
                        dns_lookup_family: V4_ONLY
                        # Asymmetric TTL. A successful resolve is cached long
                        # (host_ttl) and refreshed lazily (dns_refresh_rate) — a
                        # sandbox's pod IP is stable for its lifetime, so there's no
                        # value in churning it. A *failure* is retried fast
                        # (dns_failure_refresh_rate), so a sandbox dialed before its
                        # record exists re-resolves within ~1s instead of serving
                        # the cached failure for the full host_ttl.
                        host_ttl: 300s
                        dns_refresh_rate: 60s
                        dns_failure_refresh_rate:
                          base_interval: 1s
                          max_interval: 1s
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: main
                  virtual_hosts:
                    - name: gateway
                      domains: ["*"]
                      routes:
                        # Create leg (design §3, §8). Routed on the
                        # x-hiver-image header to the per-image cluster (one
                        # MAGLEV cluster below per image, resolving the image's
                        # headless Service to its individual pod IPs). The path
                        # is rewritten /v1/sandboxes/ → /v1/ so the pod's
                        # sandboxd receives it on its native POST /v1/{key} pack
                        # endpoint. These must precede the /sandbox/ execute leg
                        # and the /controller/ catch-all. Generated from
                        # .Values.sandboxServices.
                        {{- range $name, $img := .Values.sandboxServices }}
                        - match:
                            prefix: "/v1/sandboxes/"
                            headers:
                              - name: "x-hiver-image"
                                string_match:
                                  exact: "{{ $name }}"
                          route:
                            cluster: {{ $name }}
                            regex_rewrite:
                              pattern:
                                regex: "^/v1/sandboxes/"
                              substitution: "/v1/"
                            timeout: 0s
                            # Consistent-hash the create onto one pack host by
                            # the caller's key (x-hiver-key header), so every
                            # get-or-create for a key lands on the same pod. That
                            # pod owns the sandbox and returns its routing id; the
                            # /sandbox/<id> execute leg then dials it directly, so
                            # the hash only has to be stable, not authoritative.
                            # Paired with lb_policy: MAGLEV on the cluster below.
                            # A request missing the header falls back to random
                            # endpoint selection.
                            hash_policy:
                              - header:
                                  header_name: "x-hiver-key"
                            # The pack pods carry no readiness probe, so the
                            # Service endpoint is live before sandboxd is listening
                            # (connection-refused window). Retry instead of failing
                            # the create: connection-level retries re-load-balance
                            # across the Service's endpoints, and the create is
                            # idempotent by key so re-attempting is safe.
                            retry_policy:
                              retry_on: "connect-failure,refused-stream,reset,unavailable"
                              num_retries: 5
                              retry_back_off:
                                base_interval: 0.5s
                                max_interval: 5s
                        {{- end }}
                        - match:
                            prefix: "/controller/"
                          route:
                            cluster: controller
                            prefix_rewrite: "/"
                            timeout: 0s
                        - match:
                            prefix: "/sandbox/"
                          route:
                            cluster: dynamic_forward_proxy
                            regex_rewrite:
                              pattern:
                                regex: "^/sandbox/[^/]+"
                              substitution: ""
                            timeout: 0s
                            # Re-attempt a resumed sandbox that refused the first
                            # connection rather than returning the cached failure;
                            # paired with the short DNS host_ttl above so the retry
                            # resolves fresh.
                            retry_policy:
                              retry_on: "connect-failure,refused-stream,reset,unavailable"
                              num_retries: 5
                              retry_back_off:
                                base_interval: 0.5s
                                max_interval: 5s

  clusters:
    - name: controller
      connect_timeout: 30s
      type: STRICT_DNS
      load_assignment:
        cluster_name: controller
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: controller
                      port_value: {{ .Values.controller.port }}

    # One MAGLEV cluster per image (design §5, §8). The create routes above
    # match the x-hiver-image header to one of these and consistent-hash on
    # x-hiver-key. STRICT_DNS against the image's *headless* Service returns one
    # A record per pod, so Envoy sees the individual pack hosts as endpoints and
    # hashes across them itself (a ClusterIP Service would collapse to a single
    # VIP and hand load-balancing to kube-proxy, defeating the hash). MAGLEV
    # gives even distribution with minimal reshuffling when the pod set changes.
    # Cross-namespace FQDN so the gateway in the control-plane namespace can
    # resolve Services in the sandbox namespace.
    {{- range $name, $img := .Values.sandboxServices }}
    - name: {{ $name }}
      connect_timeout: 30s
      type: STRICT_DNS
      lb_policy: MAGLEV
      load_assignment:
        cluster_name: {{ $name }}
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{ $name }}.{{ $.Values.namespaces.sandbox }}.svc.cluster.local
                      port_value: {{ $.Values.sandboxPort }}
    {{- end }}

    - name: dynamic_forward_proxy
      connect_timeout: 30s
      lb_policy: CLUSTER_PROVIDED
      cluster_type:
        name: envoy.clusters.dynamic_forward_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.clusters.dynamic_forward_proxy.v3.ClusterConfig
          # Must match the filter's dns_cache_config above (shared by name).
          dns_cache_config:
            name: dynamic_forward_proxy_cache_config
            dns_lookup_family: V4_ONLY
            host_ttl: 300s
            dns_refresh_rate: 60s
            dns_failure_refresh_rate:
              base_interval: 1s
              max_interval: 1s
{{- end -}}
